// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"

#include "DisplayClusterConfigurationTypes_Enums.h"

class FDisplayClusterViewport;
class ADisplayClusterRootActor;
class UDisplayClusterConfigurationViewport;

struct FDisplayClusterConfigurationICVFX_OverlayAdvancedRenderSettings;
struct FDisplayClusterConfigurationPostRender_Override;
struct FDisplayClusterConfigurationPostRender_BlurPostprocess;
struct FDisplayClusterConfigurationViewport_Overscan;
struct FDisplayClusterConfigurationPostRender_GenerateMips;
struct FDisplayClusterConfigurationProjection;

class FDisplayClusterViewportConfigurationHelpers
{
public:
	static void UpdateViewportStereoMode(FDisplayClusterViewport& DstViewport, const EDisplayClusterConfigurationViewport_StereoMode StereoMode);
	
	static void UpdateViewportSetting_OverlayRenderSettings(FDisplayClusterViewport& DstViewport, const FDisplayClusterConfigurationICVFX_OverlayAdvancedRenderSettings& InOverlaySettings);
	static void UpdateViewportSetting_Override(FDisplayClusterViewport& DstViewport, const FDisplayClusterConfigurationPostRender_Override& InOverride);

	static void UpdateViewportSetting_PostprocessBlur(FDisplayClusterViewport& DstViewport, const FDisplayClusterConfigurationPostRender_BlurPostprocess& InBlurPostprocess);
	static void UpdateViewportSetting_Overscan(FDisplayClusterViewport& DstViewport, const FDisplayClusterConfigurationViewport_Overscan& InOverscan);
	static void UpdateViewportSetting_GenerateMips(FDisplayClusterViewport& DstViewport, const FDisplayClusterConfigurationPostRender_GenerateMips& InGenerateMips);

	static void UpdateBaseViewportSetting(FDisplayClusterViewport& DstViewport, ADisplayClusterRootActor& RootActor, const UDisplayClusterConfigurationViewport& InConfigurationViewport);

	static void UpdateProjectionPolicy(FDisplayClusterViewport& DstViewport, const FDisplayClusterConfigurationProjection* InConfigurationProjectionPolicy = nullptr);
};
