// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

//#define UE_DETECT_DELEGATES_RACE_CONDITIONS 1

#if !defined(UE_DETECT_DELEGATES_RACE_CONDITIONS)
	#define UE_DETECT_DELEGATES_RACE_CONDITIONS 0
#endif

#if UE_DETECT_DELEGATES_RACE_CONDITIONS
	#include "Misc/MTAccessDetector.h"
	#define UE_DELEGATES_MT_ACCESS_DETECTOR UE_MT_DECLARE_RW_FULLY_RECURSIVE_ACCESS_DETECTOR
	#define UE_DELEGATES_MT_SCOPED_WRITE_ACCESS UE_MT_SCOPED_WRITE_ACCESS
	#define UE_DELEGATES_MT_SCOPED_READ_ACCESS UE_MT_SCOPED_READ_ACCESS
#else
	#define UE_DELEGATES_MT_ACCESS_DETECTOR(...)
	#define UE_DELEGATES_MT_SCOPED_WRITE_ACCESS(...)
	#define UE_DELEGATES_MT_SCOPED_READ_ACCESS(...)
#endif
