// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#if ELECTRA_HTTPSTREAM_LIBCURL

#include "Curl/CurlElectra.h"

#if ELECTRA_HTTPSTREAM_XCURL == 0
#ifdef ELECTRA_HTTPSTREAM_CURL_PLATFORM_USE_SHARE
#define ELECTRA_HTTPSTREAM_CURL_USE_SHARE ELECTRA_HTTPSTREAM_CURL_PLATFORM_USE_SHARE
#else
#define ELECTRA_HTTPSTREAM_CURL_USE_SHARE 1
#endif
#define ELECTRA_HTTPSTREAM_CURL_POST_VIA_INFILESIZE 0
#define ELECTRA_HTTPSTREAM_CURL_DO_GLOBAL_INIT 0
#else
#ifdef ELECTRA_HTTPSTREAM_CURL_PLATFORM_USE_SHARE
#define ELECTRA_HTTPSTREAM_CURL_USE_SHARE ELECTRA_HTTPSTREAM_CURL_PLATFORM_USE_SHARE
#else
#define ELECTRA_HTTPSTREAM_CURL_USE_SHARE 0
#endif
#define ELECTRA_HTTPSTREAM_CURL_POST_VIA_INFILESIZE 1
#define ELECTRA_HTTPSTREAM_CURL_USE_XFERINFO 1
#define ELECTRA_HTTPSTREAM_CURL_USE_MULTIPOLL 1
#define ELECTRA_HTTPSTREAM_CURL_DO_GLOBAL_INIT 1
#endif

#ifndef LIBCURL_VERSION_NUM
#define LIBCURL_VERSION_NUM 0
#endif

#ifndef ELECTRA_HTTPSTREAM_CURL_USE_XFERINFO
#if LIBCURL_VERSION_NUM >= 0x072200
#define ELECTRA_HTTPSTREAM_CURL_USE_XFERINFO 1
#else
#define ELECTRA_HTTPSTREAM_CURL_USE_XFERINFO 0
#endif
#endif

#ifndef ELECTRA_HTTPSTREAM_CURL_USE_MULTIPOLL
#if LIBCURL_VERSION_NUM >= 0x074200
#define ELECTRA_HTTPSTREAM_CURL_USE_MULTIPOLL 1
#else
#define ELECTRA_HTTPSTREAM_CURL_USE_MULTIPOLL 0
#endif
#endif

// Set this to 1 to allow aborts in Curl callbacks. This does not seem to work with xCurl though.
#define ELECTRA_HTTPSTREAM_CURL_ALLOW_CANCEL_IN_CALLBACKS 0

// In all but shipping builds we allow disabling of security checks.
#if !UE_BUILD_SHIPPING
#define ELECTRA_HTTPSTREAM_CURL_ALLOW_UNSAFE_CONNECTIONS_FOR_DEBUGGING 1
#else
#define ELECTRA_HTTPSTREAM_CURL_ALLOW_UNSAFE_CONNECTIONS_FOR_DEBUGGING 0
#endif

#define ELECTRA_HTTPSTREAM_CURL_VERBOSE_DEBUGLOG 0


#endif // ELECTRA_HTTPSTREAM_LIBCURL
