// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once


#define ERRCODE_INTERNAL_LINUX_AUDIO_DECODER_NOT_SUPPORTED		  	1
#define ERRCODE_INTERNAL_LINUX_OUT_OF_MEMORY						2
#define ERRCODE_INTERNAL_LINUX_COULD_NOT_CREATE_AUDIO_DECODER		3
#define ERRCODE_INTERNAL_LINUX_COULD_NOT_CREATE_SAMPLE_POOL			4
#define ERRCODE_INTERNAL_LINUX_COULD_NOT_GET_SAMPLE_BUFFER			5
#define ERRCODE_INTERNAL_LINUX_FAILED_TO_PARSE_CSD					6
#define ERRCODE_INTERNAL_LINUX_FAILED_TO_DECODE_AUDIO				7
#define ERRCODE_INTERNAL_LINUX_AUDIO_OUTPUT_BUFFER_TOO_SMALL		8
#define ERRCODE_INTERNAL_LINUX_UNSUPPORTED_NUMBER_OF_AUDIO_CHANNELS	9
#define ERRCODE_INTERNAL_LINUX_UNSUPPORTED_DECODER_OUTPUT_FORMAT	10

#define ERRCODE_INTERNAL_LINUX_VIDEO_DECODER_NOT_SUPPORTED			101
#define ERRCODE_INTERNAL_LINUX_COULD_NOT_CREATE_VIDEO_DECODER		102
#define ERRCODE_INTERNAL_LINUX_COULD_NOT_CREATE_IMAGE_POOL			103
#define ERRCODE_INTERNAL_LINUX_COULD_NOT_GET_OUTPUT_BUFFER			104
#define ERRCODE_INTERNAL_LINUX_FAILED_TO_DECODE_VIDEO				105
#define ERRCODE_INTERNAL_LINUX_NO_VIDEO_CSD							106
#define ERRCODE_INTERNAL_LINUX_BAD_VIDEO_CSD						107
#define ERRCODE_INTERNAL_LINUX_FAILED_TO_CREATE_BLOCK_BUFFER		108
#define ERRCODE_INTERNAL_LINUX_FAILED_TO_CREATE_SAMPLE_BUFFER		109
