//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatasmithRevitResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatasmithRevitResources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Auto Sync.
        /// </summary>
        public static string ButtonAutoSync {
            get {
                return ResourceManager.GetString("ButtonAutoSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Direct Link Auto Sync.
        /// </summary>
        public static string ButtonAutoSyncHint {
            get {
                return ResourceManager.GetString("ButtonAutoSyncHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string ButtonConnections {
            get {
                return ResourceManager.GetString("ButtonConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Connections.
        /// </summary>
        public static string ButtonConnectionsHint {
            get {
                return ResourceManager.GetString("ButtonConnectionsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Datasmith file.
        /// </summary>
        public static string ButtonExport3DView {
            get {
                return ResourceManager.GetString("ButtonExport3DView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Datasmith file.
        /// </summary>
        public static string ButtonExport3DViewHint {
            get {
                return ResourceManager.GetString("ButtonExport3DViewHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string ButtonMessages {
            get {
                return ResourceManager.GetString("ButtonMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Messages.
        /// </summary>
        public static string ButtonMessagesHint {
            get {
                return ResourceManager.GetString("ButtonMessagesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ButtonSettings {
            get {
                return ResourceManager.GetString("ButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Settings.
        /// </summary>
        public static string ButtonSettingsHint {
            get {
                return ResourceManager.GetString("ButtonSettingsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize.
        /// </summary>
        public static string ButtonSync {
            get {
                return ResourceManager.GetString("ButtonSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize with Direct Link.
        /// </summary>
        public static string ButtonSyncHint {
            get {
                return ResourceManager.GetString("ButtonSyncHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasmith.
        /// </summary>
        public static string DatasmithTabName {
            get {
                return ResourceManager.GetString("DatasmithTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ExportOptionsDialog_ButtonOK {
            get {
                return ResourceManager.GetString("ExportOptionsDialog_ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No views selected for export! Please select at least one 3D view..
        /// </summary>
        public static string ExportOptionsDialog_MessageNoViewsSelected {
            get {
                return ResourceManager.GetString("ExportOptionsDialog_MessageNoViewsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 3D Views.
        /// </summary>
        public static string ExportOptionsDialog_Select3DViews {
            get {
                return ResourceManager.GetString("ExportOptionsDialog_Select3DViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreal Datasmith Export - Debug Options.
        /// </summary>
        public static string ExportOptionsDialog_Title {
            get {
                return ResourceManager.GetString("ExportOptionsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Log File.
        /// </summary>
        public static string ExportOptionsDialog_WriteLogFile {
            get {
                return ResourceManager.GetString("ExportOptionsDialog_WriteLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a &apos;.log&apos; file aside the &apos;.udatasmith&apos; file.\nThis log file records some details about the exported Revit elements.\nThe log file can become quite big for complex 3D views..
        /// </summary>
        public static string ExportOptionsDialog_WriteLogFileTooltip {
            get {
                return ResourceManager.GetString("ExportOptionsDialog_WriteLogFileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string MessagesDialog_ButtonClear {
            get {
                return ResourceManager.GetString("MessagesDialog_ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MessagesDialog_ButtonClose {
            get {
                return ResourceManager.GetString("MessagesDialog_ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreal Datasmith Export - Messages.
        /// </summary>
        public static string MessagesDialog_Title {
            get {
                return ResourceManager.GetString("MessagesDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasmith.
        /// </summary>
        public static string RibbonSection_Datasmith {
            get {
                return ResourceManager.GetString("RibbonSection_Datasmith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Link.
        /// </summary>
        public static string RibbonSection_DirectLink {
            get {
                return ResourceManager.GetString("RibbonSection_DirectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Export.
        /// </summary>
        public static string RibbonSection_FileExport {
            get {
                return ResourceManager.GetString("RibbonSection_FileExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Groups.
        /// </summary>
        public static string SettingsDialog_AddGroupsDialogTitle {
            get {
                return ResourceManager.GetString("SettingsDialog_AddGroupsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group....
        /// </summary>
        public static string SettingsDialog_ButtonAddGroups {
            get {
                return ResourceManager.GetString("SettingsDialog_ButtonAddGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SettingsDialog_ButtonClose {
            get {
                return ResourceManager.GetString("SettingsDialog_ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected.
        /// </summary>
        public static string SettingsDialog_ButtonRemoveGroups {
            get {
                return ResourceManager.GetString("SettingsDialog_ButtonRemoveGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasmith Export Settings.
        /// </summary>
        public static string SettingsDialog_DialogTitle {
            get {
                return ResourceManager.GetString("SettingsDialog_DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertion Point.
        /// </summary>
        public static string SettingsDialog_InsertionPoint {
            get {
                return ResourceManager.GetString("SettingsDialog_InsertionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change world origin for all exported elements.
        /// </summary>
        public static string SettingsDialog_InsertionPointTooltip {
            get {
                return ResourceManager.GetString("SettingsDialog_InsertionPointTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Export Filter.
        /// </summary>
        public static string SettingsDialog_LabelMatchGroups {
            get {
                return ResourceManager.GetString("SettingsDialog_LabelMatchGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Parameter Names.
        /// </summary>
        public static string SettingsDialog_LabelMatchParamNames {
            get {
                return ResourceManager.GetString("SettingsDialog_LabelMatchParamNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify parameters (medata) export filter that will be used during DirectLink synchronization. Only parameters that match the filter will be exported as metadata..
        /// </summary>
        public static string SettingsDialog_LabelMetadataDescription {
            get {
                return ResourceManager.GetString("SettingsDialog_LabelMetadataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of Tessellation.
        /// </summary>
        public static string SettingsDialog_LevelOfTesselation {
            get {
                return ResourceManager.GetString("SettingsDialog_LevelOfTesselation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 to 15 : Revit will use the suggested level of detail when tessellating faces.\nUsing a value close to the middle of the range yields a very reasonable tessellation.\nRevit uses level 8 as its &apos;normal&apos; level of detail..
        /// </summary>
        public static string SettingsDialog_LevelOfTesselationTooltip {
            get {
                return ResourceManager.GetString("SettingsDialog_LevelOfTesselationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter what metadata to export by adding allowed paramter groups..
        /// </summary>
        public static string SettingsDialog_MetadataFilterTooltip {
            get {
                return ResourceManager.GetString("SettingsDialog_MetadataFilterTooltip", resourceCulture);
            }
        }
    }
}
