// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "ProfilingDebugging/CpuProfilerTrace.h"
#include "Trace/Trace.h"

#ifndef	UE_AUDIO_PROFILERTRACE_ENABLED
	#define UE_AUDIO_PROFILERTRACE_ENABLED UE_TRACE_ENABLED && !UE_BUILD_SHIPPING
#endif // UE_AUDIO_PROFILERTRACE_ENABLED

#if	UE_AUDIO_PROFILERTRACE_ENABLED
	#define AUDIO_MIXER_TRACE_CPUPROFILER_EVENT_SCOPE(Name) TRACE_CPUPROFILER_EVENT_SCOPE(Name)
	AUDIOMIXERCORE_API UE_TRACE_CHANNEL_EXTERN(AudioChannel);
	AUDIOMIXERCORE_API UE_TRACE_CHANNEL_EXTERN(AudioMixerChannel);
#else
	#if CPUPROFILERTRACE_ENABLED
		#define AUDIO_MIXER_TRACE_CPUPROFILER_EVENT_SCOPE(Name) TRACE_CPUPROFILER_EVENT_SCOPE(Name)
	#else // !CPUPROFILERTRACE_ENABLED
		#define AUDIO_MIXER_TRACE_CPUPROFILER_EVENT_SCOPE(Name)
	#endif
#endif
