// Copyright Epic Games, Inc. All Rights Reserved.

#include "DisplayClusterProjectionLog.h"


DEFINE_LOG_CATEGORY(LogDisplayClusterProjection);
DEFINE_LOG_CATEGORY(LogDisplayClusterProjectionCamera);
DEFINE_LOG_CATEGORY(LogDisplayClusterProjectionDomeprojection);
DEFINE_LOG_CATEGORY(LogDisplayClusterProjectionEasyBlend);
DEFINE_LOG_CATEGORY(LogDisplayClusterProjectionManual);
DEFINE_LOG_CATEGORY(LogDisplayClusterProjectionMesh);
DEFINE_LOG_CATEGORY(LogDisplayClusterProjectionMPCDI);
DEFINE_LOG_CATEGORY(LogDisplayClusterProjectionSimple);
DEFINE_LOG_CATEGORY(LogDisplayClusterProjectionVIOSO);
