// Copyright Epic Games, Inc. All Rights Reserved.

#include "../Common.ush"

StructuredBuffer<uint> InputCountBuffer;
RWBuffer<uint> IndirectDispatchArgsOut;
uint Multiplier;
uint Divisor;
uint InputCountOffset;

[numthreads(1, 1, 1)]
void InitIndirectArgs1DCS(uint3 DTID : SV_DispatchThreadID)
{
	uint GroupCount = (InputCountBuffer[InputCountOffset] * Multiplier + Divisor - 1U) / Divisor;

	IndirectDispatchArgsOut[0] = GroupCount;
	IndirectDispatchArgsOut[1] = 1;
	IndirectDispatchArgsOut[2] = 1;
}
