// Copyright Epic Games, Inc. All Rights Reserved.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Horde.Server.Streams;
using Horde.Server.Utilities;
using MongoDB.Bson;

namespace Horde.Server.Jobs.TestData
{	
	/// <summary>
	/// Collection of test data documents
	/// </summary>
	public interface ITestDataCollection
	{
		/// <summary>
		/// Gets the tests running in provided streams
		/// </summary>
		/// <param name="streamIds"></param>
		/// <returns></returns>
		Task<List<ITestStream>> FindTestStreams(StreamId[] streamIds);

		/// <summary>
		/// 
		/// </summary>
		/// <param name="streamIds"></param>
		/// <param name="metaIds"></param>
		/// <param name="testIds"></param>
		/// <param name="suiteIds"></param>
		/// <param name="minCreateTime"></param>
		/// <param name="maxCreateTime"></param>
		/// <param name="minChange"></param>
		/// <param name="maxChange"></param>
		/// <returns></returns>
		Task<List<ITestDataRef>> FindTestRefs(StreamId[] streamIds, TestMetaId[]? metaIds = null, TestId[]? testIds = null, TestSuiteId[]? suiteIds = null, DateTime? minCreateTime = null, DateTime? maxCreateTime = null, int? minChange = null, int? maxChange = null);


		/// <summary>
		/// Find test details
		/// </summary>
		/// <param name="ids"></param>
		/// <returns></returns>
		Task<List<ITestDataDetails>> FindTestDetails(TestRefId[] ids);

		/// <summary>
		/// Find tests
		/// </summary>
		/// <param name="testIds"></param>
		/// <returns></returns>
		Task<List<ITest>> FindTests(TestId[] testIds);

		/// <summary>
		/// Find test suites
		/// </summary>
		/// <param name="suiteIds"></param>
		/// <returns></returns>
		Task<List<ITestSuite>> FindTestSuites(TestSuiteId[] suiteIds);

		/// <summary>
		/// Creates a new test data document
		/// </summary>
		/// <param name="job">The job containing the step</param>
		/// <param name="step">The step producing the data</param>
		/// <param name="data">The test data generated by the job step</param>
		/// <returns>The new stream document</returns>
		Task<List<ITestData>> AddAsync(IJob job, IJobStep step, (string key, BsonDocument value)[] data);

		/// <summary>
		/// Gets a stream by ID
		/// </summary>
		/// <param name="id">Unique id of the stream</param>
		/// <returns>The stream document</returns>
		Task<ITestData?> GetAsync(ObjectId id);

		/// <summary>
		/// Searches for test data that matches a set of criteria
		/// </summary>
		/// <param name="streamId">The stream id</param>
		/// <param name="minChange">The minimum changelist number to return (inclusive)</param>
		/// <param name="maxChange">The maximum changelist number to return (inclusive)</param>
		/// <param name="jobId">The job id</param>
		/// <param name="stepId">The unique step id</param>
		/// <param name="key">Key identifying the result to return</param>
		/// <param name="index">Offset within the results to return</param>
		/// <param name="count">Number of results to return</param>
		/// <returns>The stream document</returns>
		Task<List<ITestData>> FindAsync(StreamId? streamId, int? minChange, int? maxChange, JobId? jobId, SubResourceId? stepId, string? key = null, int index = 0, int count = 10);


		/// <summary>
		/// Find test meta data
		/// </summary>
		/// <param name="projectNames"></param>
		/// <param name="platforms"></param>
		/// <param name="configurations"></param>
		/// <param name="buildTargets"></param>
		/// <param name="rhi"></param>
		/// <param name="variation"></param>
		/// <param name="metaIds"></param>
		/// <returns></returns>
		Task<List<ITestMeta>> FindTestMeta(string[]? projectNames = null, string[]? platforms = null, string[]? configurations = null, string[]? buildTargets = null, string? rhi = null, string? variation = null, TestMetaId[]? metaIds = null);

		/// <summary>
		/// Delete the test data
		/// </summary>
		/// <param name="id">Unique id of the test data</param>
		/// <returns>Async task</returns>
		Task DeleteAsync(ObjectId id);

		/// <summary>
		/// Prune test data from collection
		/// </summary>
		/// <returns></returns>
		public Task PruneDataAsync();

		/// <summary>
		/// Run a tick on the collection
		/// </summary>
		/// <returns></returns>
		public Task<bool> UpdateAsync(int retainMonths);

		/// <summary>
		/// Upgrades the collection
		/// </summary>
		public Task UpgradeAsync();
	}
}
