// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once


#define ERRCODE_INTERNAL_APPLE_OUT_OF_MEMORY						1
#define ERRCODE_INTERNAL_APPLE_COULD_NOT_CREATE_AUDIO_DECODER		2
#define ERRCODE_INTERNAL_APPLE_COULD_NOT_CREATE_SAMPLE_POOL			3
#define ERRCODE_INTERNAL_APPLE_COULD_NOT_GET_SAMPLE_BUFFER			4
#define ERRCODE_INTERNAL_APPLE_FAILED_TO_PARSE_CSD					5
#define ERRCODE_INTERNAL_APPLE_FAILED_TO_DECODE_AUDIO				6
#define ERRCODE_INTERNAL_APPLE_AUDIO_OUTPUT_BUFFER_TOO_SMALL		7
#define ERRCODE_INTERNAL_APPLE_UNSUPPORTED_NUMBER_OF_AUDIO_CHANNELS	8

#define ERRCODE_INTERNAL_APPLE_COULD_NOT_CREATE_VIDEO_DECODER		100
#define ERRCODE_INTERNAL_APPLE_COULD_NOT_CREATE_IMAGE_POOL			101
#define ERRCODE_INTERNAL_APPLE_COULD_NOT_GET_OUTPUT_BUFFER			102
#define ERRCODE_INTERNAL_APPLE_FAILED_TO_DECODE_VIDEO				103
#define ERRCODE_INTERNAL_APPLE_NO_VIDEO_CSD							104
#define ERRCODE_INTERNAL_APPLE_BAD_VIDEO_CSD						105
#define ERRCODE_INTERNAL_APPLE_FAILED_TO_CREATE_BLOCK_BUFFER		110
#define ERRCODE_INTERNAL_APPLE_FAILED_TO_CREATE_SAMPLE_BUFFER		111


