// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#ifndef ELECTRA_PLATFORM_HAS_H265_DECODER
#define ELECTRA_PLATFORM_HAS_H265_DECODER 0
#endif

#ifndef ELECTRA_PLATFORM_ENABLE_HDR
#define ELECTRA_PLATFORM_ENABLE_HDR 0
#endif

#if ELECTRA_DISABLE_HDR
#undef ELECTRA_PLATFORM_ENABLE_HDR
#define ELECTRA_PLATFORM_ENABLE_HDR 0
#endif
