// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once


#define ERRCODE_INTERNAL_ANDROID_OUT_OF_MEMORY						1
#define ERRCODE_INTERNAL_ANDROID_COULD_NOT_CREATE_AUDIO_DECODER		2
#define ERRCODE_INTERNAL_ANDROID_COULD_NOT_CREATE_VIDEO_DECODER		3
#define ERRCODE_INTERNAL_ANDROID_COULD_NOT_CREATE_SAMPLE_POOL		4
#define ERRCODE_INTERNAL_ANDROID_COULD_NOT_CREATE_IMAGE_POOL		5
#define ERRCODE_INTERNAL_ANDROID_FAILED_TO_PARSE_CSD				6
#define ERRCODE_INTERNAL_ANDROID_FAILED_TO_DECODE_AUDIO				7
#define ERRCODE_INTERNAL_ANDROID_FAILED_TO_DECODE_VIDEO				8

#define ERRCODE_INTERNAL_ANDROID_NO_VIDEO_CSD						20
#define ERRCODE_INTERNAL_ANDROID_BAD_VIDEO_CSD						21

#define ERRCODE_INTERNAL_ANDROID_COULD_NOT_CONFIGURE_DECODER		30
#define ERRCODE_INTERNAL_ANDROID_COULD_NOT_START_DECODER			31
#define ERRCODE_INTERNAL_ANDROID_COULD_NOT_STOP_DECODER				32
#define ERRCODE_INTERNAL_ANDROID_COULD_NOT_GET_INPUT_BUFFER			33
#define ERRCODE_INTERNAL_ANDROID_COULD_NOT_GET_OUTPUT_BUFFER		34
#define ERRCODE_INTERNAL_ANDROID_COULD_NOT_GET_OUTPUT_FORMAT		35

#define ERRCODE_INTERNAL_ANDROID_COULD_NOT_GET_RENDER_BUFFER		40
#define ERRCODE_INTERNAL_ANDROID_RENDER_BUFFER_TOO_SMALL			41
#define ERRCODE_INTERNAL_ANDROID_COULD_NOT_FIND_OUTPUT_INFO			42

#define ERRCODE_INTERNAL_ANDROID_UNSUPPORTED_NUMBER_OF_AUDIO_CHANNELS	50

#define ERRCODE_INTERNAL_ANDROID_INTERNAL							10000

