// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#if WITH_VERSE_VM || defined(__INTELLISENSE__)

// IWYU pragma: begin_keep
#include "Containers/Array.h"
#include "Containers/StringConv.h"
#include "VVMBytecode.h"
#include "VVMClass.h"
#include "VVMContext.h"
#include "VVMValue.h"
#include "VVMWriteBarrier.h"
// IWYU pragma: end_keep

// Include autogenerated file.
#include "VVMBytecodesAndCaptures.gen.h"

#endif // WITH_VERSE_VM
