// Copyright Epic Games, Inc. All Rights Reserved.

#include "DXGIUtilities.h"

#if PLATFORM_MICROSOFT

const TCHAR* UE::DXGIUtilities::GetFormatString(DXGI_FORMAT Format)
{
	const TCHAR* Result = TEXT("");

#define DXGI_FORMAT_CASE(x) case x: Result = TEXT(#x); break;
	switch (Format)
	{
		DXGI_FORMAT_CASE(DXGI_FORMAT_R8G8B8A8_UNORM)
		DXGI_FORMAT_CASE(DXGI_FORMAT_B8G8R8A8_UNORM)
		DXGI_FORMAT_CASE(DXGI_FORMAT_B8G8R8X8_UNORM)
		DXGI_FORMAT_CASE(DXGI_FORMAT_BC1_UNORM)
		DXGI_FORMAT_CASE(DXGI_FORMAT_BC2_UNORM)
		DXGI_FORMAT_CASE(DXGI_FORMAT_BC3_UNORM)
		DXGI_FORMAT_CASE(DXGI_FORMAT_BC4_UNORM)
		DXGI_FORMAT_CASE(DXGI_FORMAT_R16G16B16A16_FLOAT)
		DXGI_FORMAT_CASE(DXGI_FORMAT_R32G32B32A32_FLOAT)
		DXGI_FORMAT_CASE(DXGI_FORMAT_UNKNOWN)
		DXGI_FORMAT_CASE(DXGI_FORMAT_R8_UNORM)
		DXGI_FORMAT_CASE(DXGI_FORMAT_D32_FLOAT_S8X24_UINT)
		DXGI_FORMAT_CASE(DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS)
		DXGI_FORMAT_CASE(DXGI_FORMAT_R32G8X24_TYPELESS)
		DXGI_FORMAT_CASE(DXGI_FORMAT_D24_UNORM_S8_UINT)
		DXGI_FORMAT_CASE(DXGI_FORMAT_R24_UNORM_X8_TYPELESS)
		DXGI_FORMAT_CASE(DXGI_FORMAT_R32_FLOAT)
		DXGI_FORMAT_CASE(DXGI_FORMAT_R16G16_UINT)
		DXGI_FORMAT_CASE(DXGI_FORMAT_R16G16_UNORM)
		DXGI_FORMAT_CASE(DXGI_FORMAT_R16G16_SNORM)
		DXGI_FORMAT_CASE(DXGI_FORMAT_R16G16_FLOAT)
		DXGI_FORMAT_CASE(DXGI_FORMAT_R32G32_FLOAT)
		DXGI_FORMAT_CASE(DXGI_FORMAT_R10G10B10A2_UNORM)
		DXGI_FORMAT_CASE(DXGI_FORMAT_R16G16B16A16_UINT)
		DXGI_FORMAT_CASE(DXGI_FORMAT_R8G8_SNORM)
		DXGI_FORMAT_CASE(DXGI_FORMAT_BC5_UNORM)
		DXGI_FORMAT_CASE(DXGI_FORMAT_R1_UNORM)
		DXGI_FORMAT_CASE(DXGI_FORMAT_R8G8B8A8_TYPELESS)
		DXGI_FORMAT_CASE(DXGI_FORMAT_B8G8R8A8_TYPELESS)
		DXGI_FORMAT_CASE(DXGI_FORMAT_BC7_UNORM)
		DXGI_FORMAT_CASE(DXGI_FORMAT_BC6H_UF16)
		default:
			Result = TEXT("");
	}
#undef DXGI_FORMAT_CASE
	return Result;
}

#endif // PLATFORM_MICROSOFT
