// Copyright Epic Games, Inc. All Rights Reserved.

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class FDatasmithFacadeDecalMaterial : FDatasmithFacadeBaseMaterial {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FDatasmithFacadeDecalMaterial(global::System.IntPtr cPtr, bool cMemoryOwn) : base(DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeDecalMaterial_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FDatasmithFacadeDecalMaterial obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DatasmithFacadeCSharpPINVOKE.delete_FDatasmithFacadeDecalMaterial(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public FDatasmithFacadeDecalMaterial(string InElementName) : this(DatasmithFacadeCSharpPINVOKE.new_FDatasmithFacadeDecalMaterial(InElementName), true) {
  }

  public string GetDiffuseTexturePathName() {
    string ret = global::System.Runtime.InteropServices.Marshal.PtrToStringUni(DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeDecalMaterial_GetDiffuseTexturePathName(swigCPtr));
    return ret;
  }

  public void SetDiffuseTexturePathName(string DiffuseTexturePathName) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeDecalMaterial_SetDiffuseTexturePathName(swigCPtr, DiffuseTexturePathName);
  }

  public string GetNormalTexturePathName() {
    string ret = global::System.Runtime.InteropServices.Marshal.PtrToStringUni(DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeDecalMaterial_GetNormalTexturePathName(swigCPtr));
    return ret;
  }

  public void SetNormalTexturePathName(string NormalTexturePathName) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeDecalMaterial_SetNormalTexturePathName(swigCPtr, NormalTexturePathName);
  }

}
