// Copyright Epic Games, Inc. All Rights Reserved.

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class FDatasmithFacadePropertyCapture : FDatasmithFacadeElement {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FDatasmithFacadePropertyCapture(global::System.IntPtr cPtr, bool cMemoryOwn) : base(DatasmithFacadeCSharpPINVOKE.FDatasmithFacadePropertyCapture_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FDatasmithFacadePropertyCapture obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DatasmithFacadeCSharpPINVOKE.delete_FDatasmithFacadePropertyCapture(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public FDatasmithFacadePropertyCapture() : this(DatasmithFacadeCSharpPINVOKE.new_FDatasmithFacadePropertyCapture(), true) {
  }

  public void SetPropertyPath(string Path) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadePropertyCapture_SetPropertyPath(swigCPtr, Path);
  }

  public string GetPropertyPath() {
    string ret = global::System.Runtime.InteropServices.Marshal.PtrToStringUni(DatasmithFacadeCSharpPINVOKE.FDatasmithFacadePropertyCapture_GetPropertyPath(swigCPtr));
    return ret;
  }

  public EDatasmithFacadePropertyCategory GetCategory() {
    EDatasmithFacadePropertyCategory ret = (EDatasmithFacadePropertyCategory)DatasmithFacadeCSharpPINVOKE.FDatasmithFacadePropertyCapture_GetCategory(swigCPtr);
    return ret;
  }

}
