// Copyright Epic Games, Inc. All Rights Reserved.

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class FDatasmithFacadeSubsequenceAnimation : FDatasmithFacadeBaseAnimation {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FDatasmithFacadeSubsequenceAnimation(global::System.IntPtr cPtr, bool cMemoryOwn) : base(DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeSubsequenceAnimation_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FDatasmithFacadeSubsequenceAnimation obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DatasmithFacadeCSharpPINVOKE.delete_FDatasmithFacadeSubsequenceAnimation(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public FDatasmithFacadeSubsequenceAnimation(string InName) : this(DatasmithFacadeCSharpPINVOKE.new_FDatasmithFacadeSubsequenceAnimation(InName), true) {
  }

  public int GetStartTime() {
    int ret = DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeSubsequenceAnimation_GetStartTime(swigCPtr);
    return ret;
  }

  public void SetStartTime(int InFrameNumber) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeSubsequenceAnimation_SetStartTime(swigCPtr, InFrameNumber);
  }

  public int GetDuration() {
    int ret = DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeSubsequenceAnimation_GetDuration(swigCPtr);
    return ret;
  }

  public void SetDuration(int InDuration) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeSubsequenceAnimation_SetDuration(swigCPtr, InDuration);
  }

  public float GetTimeScale() {
    float ret = DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeSubsequenceAnimation_GetTimeScale(swigCPtr);
    return ret;
  }

  public void SetTimeScale(float InTimeScale) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeSubsequenceAnimation_SetTimeScale(swigCPtr, InTimeScale);
  }

  public FDatasmithFacadeLevelSequence GetNewSubsequence() {
    global::System.IntPtr cPtr = DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeSubsequenceAnimation_GetNewSubsequence(swigCPtr);
    FDatasmithFacadeLevelSequence ret = (cPtr == global::System.IntPtr.Zero) ? null : new FDatasmithFacadeLevelSequence(cPtr, false);
    return ret;
  }

  public void SetSubsequence(FDatasmithFacadeLevelSequence InSubsequence) {
    DatasmithFacadeCSharpPINVOKE.FDatasmithFacadeSubsequenceAnimation_SetSubsequence(swigCPtr, FDatasmithFacadeLevelSequence.getCPtr(InSubsequence));
  }

}
